  # Site Info
title:              "The Adventures of Tintin"
google_verify:       # Put your Google Verification here
google_analytics:    # Put your Google Analytics code

# Site Settings
baseurl:            "/adventures" # Base URL must end WITHOUT a slash, default: ""
permalink:          /:title # Post permalink
mathjax:            true  # enables support for mathjax - set to false to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt", "Gemfile" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor" ]
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - tzinfo

feed:
  path: rss/index.xml

defaults:
  - scope:
      path:         ""
    values:
      layout:       "default"
  - scope:
      type:         "pages"
    values:
      layout:       "page"
  - scope:
      type:         "posts"
    values:
      layout:       "post"